### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by johnwarburton** [LMAX-Exchange/puppet-sfptpd#1]
Hi
Would you be willing to accept new PRs? I recently did the work to get the module to pass puppet 7 testing and was wondering if you would like it here?

Cheers
John

**Comment by lukebigum** [comment]
Hi John,

Yeah sure.  We still use this internally (I should check any of our local mods have made it up here), and we use it on Puppet 7 as well.

-Luke

**Comment by johnwarburton** [comment]
Thanks Luke

I'll put this on hold until your internal mods are up
The only actual change I would propose is to surface the "new" `epoch_guard` parameter with its default `prevent-sync` so its visibly present/reassuring. You may already have that in the module?

Cheers
John

**Comment by lukebigum** [comment]
Apologies, John. I looked at any local modifications and found that all of our internal changes had already been pushed up (and thus probably excluding many new features in the latest `sfptpd` versions).

I just forgot to tell you and only remembered now.

If you submit your PRs I can merge them.

**Comment by johnwarburton** [comment]
Hi @lukebigum 

Sorry, this dropped off my radar. Please find PR #2 with `epoch_guard` support, puppet 7 client and EL9 support

Note - this was tested on EL9 with `ntpsec` (from EPEL) as the NTP package

Please let me know if you need anything else

Regards

John

**Comment by lukebigum** [comment]
Thanks, merged.  I'll try it out internally soon-ish (on EL8).

**Comment by johnwarburton** [comment]
Hi @lukebigum - I wonder if you had time to test this and if its ready to bump as a puppet forge release?

Thanks

**Comment by lukebigum** [comment]
@johnwarburton try that - just pushed v5, deprecating old Puppet versions.  I haven't done that in a while, we use pure Git internally, not the Forge.  If you need any other changes let me know.

**Comment by johnwarburton** [comment]
Thanks @lukebigum - works like a charm!

thanks again for your module and your help getting this update over the line!
